### ISSUE TITLE
Passing props to scene in getSceneClass.

### ISSUE THREAD

**Issue by joshuapinter** [exponentjs/ex-navigator#100]
I'm trying to pass an object to an Edit page. 

Without passing anything, **this works fine**: 

``` js
getAddRelationshipRoute(relationship) {
    return {
      getSceneClass(navigator) {
        require('./AddRelationship');
      },
```

However, when trying to pass the props, **this doesn't work**: 

``` js
getAddRelationshipRoute(relationship) {
    return {
      getSceneClass(navigator) {
        let AddRelationship = require('./AddRelationship');
        return <AddRelationship relationship={relationship} navigator={navigator} />;
      },
```

I get the following error message: 

![screenshot 2016-02-26 08 54 30](https://cloud.githubusercontent.com/assets/180819/13357229/90c036a8-dc66-11e5-911a-f3c2bc2c3a5a.png)

**Comment by samuelkraft** [comment]
Use renderScene instead. Here's from the docs:

``` js
// You can also render a scene yourself when you need more control over
// the props of the scene component
renderScene(navigator) {
  let ProfileScene = require('./ProfileScene');
  return <ProfileScene navigator={navigator} profile={profile} />;
}
```

**Comment by joshuapinter** [comment]
![facepalm](https://cloud.githubusercontent.com/assets/180819/13358393/4cf37de4-dc6c-11e5-9288-54d34fef5e07.gif)

Didn't even see that change. Thanks!

**Comment by pavlelekic** [comment]
Is there a way to set props for all scenes, like without writing this manually for every scene? If I have 50 scenes, and I wan some property to pass down to all scenes?

I have a top level component (above navigator), that is supposed to pass props to navigator, and I want navigator to pass those props down to whatever scene is currently displayed. Is that possible?
