### ISSUE TITLE
Integration with TabBarIOS

### ISSUE THREAD

**Issue by pulpfree** [exponentjs/ex-navigator#102]
I'm new to react native and am hoping someone can provide some tips or steer me in the right direction regarding integrating ex-navigator with TabBarIOS. Currently my layout looks like below with the Menu a TabBarIOS component. My question is, how can integrate routes into the menu? Or do the ExNavigator 'scenes' have to encapsulate the menu components? This last option isn't really good for my layout though. BTW I'm using redux and did read about using actions to change routes, is that something I should look at?
Appreciate any help.

```
render() {
  return (
    <View style={styles.container}>
      <ExNavigator
        initialRoute={Router.getHomeRoute()}
        style={{flex: 1}}
        sceneStyle={{paddingTop: 64}}
      />
      <Menu router={Router} />
    </View>
   )
 }
```

**Comment by samuelkraft** [comment]
This repo has an example using ExNavigator and TabNavigator. Setup should be the same with TabBarIOS: https://github.com/wesley1001/ex-navigator-tabnavigator-demo

**Comment by pulpfree** [comment]
@samuelkraft this looks perfect. Had a feeling the router might have to render the tab bar. Thanks for the help!
