### ISSUE TITLE
what's the best way to set state of scene component from rightButton?

### ISSUE THREAD

**Issue by faceyspacey** [exponentjs/ex-navigator#106]
Without having to use Redux, I'm wondering what the best practices way is to set the state of the corresponding component to a scene. It seems very counter-intuitive that I have to pass down such methods from components higher up the tree--ultimately that means you can pass a handler to `renderRightButton` that only controls a parent's state, but the parallel component that the right button is rendered with. 

I must be missing something, there has to be a way without having to resolve to using Redux or creating your own navigation bar within the scene.

**Comment by faceyspacey** [comment]
I found a decent way: get a ref to the scene component in your route function via a closure, and then in right button `onPress` handler call a method on that component. I guess that's good enough. If anyone knows any better ways, I'd still love to know though.

**Comment by ide** [comment]
There isn't a great solution here. It's sort of inherent in how the underlying Navigator is written. Here are three options, two of which you've mentioned:
- Use a global Redux store and have the RightButton and Scene components subscribe to it, and communicate via the Redux store.
- Capture a ref to the Scene component in a scope that the RightButton has access to.
- (What we do) In the function that creates our route, we create an EventEmitter and pass it into the RightButton and Scene components as a prop. Then the two components can communicate via emitting events.
