### ISSUE TITLE
Working together with react-redux

### ISSUE THREAD

**Issue by pietropizzi** [exponentjs/ex-navigator#11]
This is more a question than an issue.

I was wondering how I can best connect my router with my Redux store. react-redux's `connect` method only works with components. Do you usually make your router an component? How do you hook it up to the store and to dispatching actions?

**Comment by ide** [comment]
We don't store routing data anywhere (I guess it's implicitly in the Navigator's route stack). If you wanted to put it in redux you would use plain redux -- no react-redux at all -- and invoke push/pop calls as appropriate.

**Comment by pietropizzi** [comment]
It's not necessary about storing the route stack but more about invoking stuff from a route. E.g. I have a route that has a right button in the navbar, which should invoke an action when pressed. So I have to pass it the store somehow. With plain redux I am not sure how to get a hold of the store.

**Comment by pietropizzi** [comment]
I found a way to get hold of the store.

**Comment by grabbou** [comment]
@ide can't we just allow `passProps` on `ExNavigator` and pass it along `navigator` in `routeRenderer.renderScene`? Would be super helpful since I am connecting from my top-level component and want to pass all the actions and reducers down.

**Comment by joshhornby** [comment]
@pietropizzi Can you detail how you got hold of the store? Thanks

**Comment by pietropizzi** [comment]
@joshhornby so the way I did it is to hold on to the store when I create it and make it available.

Here's a slightly shortend version of my `lib/store.js`

``` js
import { applyMiddleware, combineReducers, createStore } from 'redux';

const rootReducer = combineReducers({ /* my reducers*/ });
const createStoreWithMiddleWare = applyMiddleware(/* my middleware */)(createStore);

var store;

export default {

  get(initialState = {}) {
    if (!store) {
      store = createStoreWithMiddleWare(rootReducer, initialState);
    }

    return store;
  }
};
```

So when you get  `lib/store` and call `get` for the first time, the store is created and passed back to you. Every following time you call `get` you just get the store.

``` js
import Store from './lib/store';

const store = Store.get();
```

**Comment by joshhornby** [comment]
thanks @pietropizzi  :+1:
