### ISSUE TITLE
problems with UIManager.measure()

### ISSUE THREAD

**Issue by jurgenphotek** [exponentjs/ex-navigator#117]
Hi, In addition to ex-navigator I am using another component from another library that positions itself based on the results of the measure fn, as described here: https://facebook.github.io/react-native/docs/nativemethodsmixin.html

unfortunately for the same navigator views that fn returns different results depending on whether it is the initial route or whether it was pushed (pageX prop returned from measure() is 0 or the same as screen width ). not sure if there is a better method to use for dimensions or some other trick to using ex-navigator to get consistent results?

thanks

**Comment by ide** [comment]
I would expect the dimensions to be measured the same everywhere but the absolute position of the component of course will differ if it's sliding in from the right.

**Comment by jurgenphotek** [comment]
hm, ok. so it somehow it needs to get dimensions post-slide

**Comment by ide** [comment]
Generally speaking, relying on pageX isn't what you want. Better to find the local X coordinate instead of the absolute one for robustness.

**Comment by jurgenphotek** [comment]
ok thanks
