### ISSUE TITLE
Element type is invalid: expected a string

### ISSUE THREAD

**Issue by XavierColombel** [exponentjs/ex-navigator#120]
I've got this error when I launch the app:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of 'Navigator'.

I've got RN 0.26.3 and React 15.0.2.

Here is my code:

![Error](http://img11.hostingpics.net/pics/517043Capturedecran20160604a023015.png)

**Comment by shulyugin** [comment]
return HomeScene instead

**Comment by ide** [comment]
@shulyugin is right, you're supposed to return a class, not an element.
