### ISSUE TITLE
How to make title center in android?

### ISSUE THREAD

**Issue by yukunwu** [exponentjs/ex-navigator#121]
In ios,we set the title,and by default it is in the center of navigator, and now i want to make title in the center in android,so I implement `renderTitle`,and make a component to render the title.

``` js
const defaultStyles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: 'red',
        alignItems: 'center',
        marginLeft:0,
        marginRight:0
    },
    title_style: {
        color: 'white',
        fontSize: 25,
        textAlign: 'center',
        margin: 0
    }
});

class Title extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            title_text: props.title_text ? props.title_text : '',
            title_style: props.title_style ? props.title_style : defaultStyles.title_style
        };
    }
    render() {
        return (<View style={defaultStyles.container}>
            <Text style={this.state.title_style}>{this.state.title_text}</Text>
        </View>);
    }
    componentWillReceiveProps(nextProps) {
        this.setState({ title_text: nextProps.title_text, title_style: nextProps.title_style });
    }
}
export default Title;
```

And in the route

``` js
renderTitle(navigator, index, state) {
    return (<Title title_text={'Title'}/>);
}
```

I try to set the style of title to make it marth_parent and fill the navigator,but the area of the title is wrap_content. How to fix it ?
![image](https://cloud.githubusercontent.com/assets/5382222/15811388/ab21dfce-2bda-11e6-8e92-19f70a63fcae.png)

Thanks.

**Comment by yukunwu** [comment]
@ide  in this [issue](https://github.com/facebook/react-native/issues/2995) , you provide an approach to use the IOS style navigator in android.

``` js
<Navigator.NavigationBar
  navigationStyles={Navigator.NavigationBar.StylesIOS}
/>
```

or

``` js
<Navigator.NavigationBar
  transitionStyles={Navigator.NavigationBar.TransitionStylesIOS}
/>
```

I try this, but it doesn't work.Go through the source code int `NavigatorNavigationBar.js` ,I only see the style code

``` js
statics: {
    Styles: NavigatorNavigationBarStyles,
    StylesAndroid: NavigatorNavigationBarStylesAndroid,
    StylesIOS: NavigatorNavigationBarStylesIOS,
}
```

How to make this work?

Thanks.

**Comment by yukunwu** [comment]
Finally, I implement the  `renderNavigationBar` method, and render a given `NavigationBar` and set the navigationStyles to `Navigator.NavigationBar.StylesIOS`,and now it is in IOS style.

``` js
render() {
    return (
        <ExNavigator
            navigationBarStyle={styles.navigationBarStyle}
            titleStyle={styles.titleStyle}
            tintColor = { navbar_tint_color }
            barButtonTextStyle={styles.barButtonTextStyle}
            barButtonIconStyle={styles.barButtonIconStyle}
            renderNavigationBar={this._renderNavigationBar.bind(this) }
            sceneStyle={styles.barSceneStyle}
            initialRoute={BaseRouter.getDashboardRoute() }/>
    );
}
_renderNavigationBar(param) {
    let navigationStyles = Navigator.NavigationBar.StylesIOS;
    return (<Navigator.NavigationBar
        routeMapper={param.routeMapper}
        style = {param.style}
        navigationStyles={navigationStyles}/>);
}
```

Something like this.

![image](https://cloud.githubusercontent.com/assets/5382222/15845123/7ea15cea-2ca2-11e6-8f94-1728014c1c73.png)

But it is not perfect,the title and the buttons is not center vertical ,on the top ,there is 20px height of statusbar,and currently we cannot impact the `Navigator.NavigationBar.StylesIOS` whith a given props,but we can rewrite the `Navigator.NavigationBar.StylesIOS.js` file and fix it.

**Comment by sudharsan1988** [comment]
It works but content seems to be blank in my end. Are you able to see the main content?

**Comment by sudharsan1988** [comment]
Just checked, I missed something in <ExNavigator>. Now it works great. Thank you
