### ISSUE TITLE
when react-native >=0.27, The code 'import ExNavigator from '@exponent/react-native-navigator'  '  is wrong 

### ISSUE THREAD

**Issue by duzhuan119** [exponentjs/ex-navigator#124]
when react-native =0.24, The code 'import ExNavigator from '@exponent/react-native-navigator'  '   is right.
when react-native >=0.27, The code 'import ExNavigator from '@exponent/react-native-navigator'  '   is wrong ,
The error is as follows:
super expression must either be null or a function not undefined

Why, What am I to do ?  thank you.

**Comment by ide** [comment]
I think the bug is in your code. We use ExNavigator in an app that runs with RN 0.27.

**Comment by mlumbroso** [comment]
I actually have the same issue, trying to use the same implementation as in the documentation.
