### ISSUE TITLE
Two export default lines in ExRouteRenderer.js

### ISSUE THREAD

**Issue by elie222** [exponentjs/ex-navigator#131]
I get this error when running my app:

```
Encountered an error while persisting cache:
> SyntaxError: /.../app/node_modules/@exponent/react-native-navigator/ExRouteRenderer.js: Only one default export allowed per module.
```

And there are indeed two lines in this file that say `export default`.

**Comment by cedoucette** [comment]
I just saw this issue also.
Apparently, it's just been fixed in 0.4.8 (1 hour after you reported this):
https://github.com/exponentjs/ex-navigator/commit/6b644659d59ed8f35f37ea56ba078a405c2c68e0
