### ISSUE TITLE
Only one default export allowed per module.

### ISSUE THREAD

**Issue by almithani** [exponentjs/ex-navigator#132]
When running a project using react-native-navigator, the packager spits out this error when it's assembling an Android bundle:

```
[node-haste] Encountered an error while persisting cache:
> SyntaxError: /<my project path>/node_modules/@exponent/react-native-navigator/ExRouteRenderer.js: Only one default export allowed per module.
>   258 | });
>   259 | 
> > 260 | export default ExRouteRenderer;
>       | ^
>   261 | 
```

Looking at ExRouteRenderer.js, it does indeed have two default export statements.  Removing the first one allows the project to run as expected.

**Comment by ide** [comment]
This is fixed, you should upgrade.
