### ISSUE TITLE
Hook up navigation bar methods to the scene state and props

### ISSUE THREAD

**Issue by varungupta85** [exponentjs/ex-navigator#134]
I know that the repo suggests using `ex-navigation` instead of this and that there isn't much active development going into this repo but I have been using this repo for some time and not in a state to move to the newer repo right now.

I wanted to know if there is a way to hook up navigation bar methods (right button, left button) to the state and props of the scene that is currently rendered in the navigator. For e.g. I have some input boxes in the scene and I want to provide a `Done` right button in the navigation bar which when clicked, collects the user inputs (state and props for the screen)  and do something with it. I am unable to find a way to achieve it using this library and wanted to check if I am missing anything or if there is an accepted pattern to achieve it.

Thanks!

cc @brentvatne @ide

**Comment by ide** [comment]
The recommended pattern is to share an EventEmitter (or another message-passing mechanism of your choice) between the components in your navigation bar (ex: Done button) and your scene component.

**Comment by varungupta85** [comment]
@ide, Thanks a lot for the tip. EventEmitter would be perfect for this use case.
