### ISSUE TITLE
setState doesn't re-render the component

### ISSUE THREAD

**Issue by iZaL** [exponentjs/ex-navigator#20]
I have a state property `isLoggedIn` which stores the state of the logged in user. and componentDidMount checks whether the user is logged in. The problem I'm facing is, If componentDidMount method returns isLoggedIn to true, the Exnavigation doesn't navigate to the home screen. It always returns the login screen regardless 

``` javascript
export default class Home extends Component {

  constructor(props) {
    super(props);
    this.state = {
      isLoggedIn: false,
    }
  }

  componentDidMount() {
    AuthService.getAuthInfo((err, authInfo)=> {
      this.setState({
        isLoggedIn: authInfo != null,
      })
    });
  }

  render() {
    let initialRoute = Router.getLoginRoute();
    if (this.state.isLoggedIn) {
      initialRoute = Router.getCategoryListRoute();
    }

    return this.renderScreen(initialRoute);
  }

  renderScreen(route) {
    return (
      <ExNavigator
        initialRoute={route}
        style={{ flex: 1 }}
        sceneStyle={{ paddingTop: 64 }}
        />
    );

  }
}
```

**Comment by ide** [comment]
This is the intended behavior and why the prop is called initialRoute instead of route (this is a React convention that uncontrolled components use). Use push/pop or immediatelyResetRouteStack to change the route after the first render.

**Comment by joshhornby** [comment]
@ide Have you got an example of this?

**Comment by ide** [comment]
@joshhornby many of the ExRoute methods like renderScene receive an ExNavigator instance. Once you have that instance you can store it whenever makes sense to you and call push/pop on it to modify the route stack.
