### ISSUE TITLE
Getting onWillFocus() upon tab changes...possible?

### ISSUE THREAD

**Issue by marcshilling** [exponentjs/ex-navigator#26]
My setup is pretty standard - a tab bar with each tab's root being an `<ExNavigator>`. I update my status bar color accordingly in the `onWillFocus()` function for each route in my router object. This works great pushing/popping between scenes within each ExNavigator, however when I switch between tabs (to each different ExNavigator component), `onWillFocus()` is not fired. I realize this isn't really an issue with your library, but I'm wondering if this is possible. I can get the ref of the `ExNavigator` on tab change no problem, but is there any way I can get the CURRENT route from that, so I can explicitly call `onWillFocus()` upon tab change?

**Comment by ide** [comment]
I believe you can go from the navigator to the navigation context, and then get the current route that way. Something like `navigator.context.currentRoute`. Longer term I'd like for Navigator to stabilize and then have TabNavigator act as another Navigator.

**Comment by marcshilling** [comment]
@ide you're right! Exactly what I needed...thanks!
