### ISSUE TITLE
Right Padding for Right Button on ExNavigator does not Match Native NavigatorIOS

### ISSUE THREAD

**Issue by cancan101** [exponentjs/ex-navigator#32]
I am using:

``` jsx
<ExNavigator
    ref="navDevice"
    style={{flex: 1, paddingTop: 65}}
    initialRoute={{
        getTitle() {return 'Devices'; },
        getSceneClass() {return DeviceList; },
        renderRightButton(navigator) {
            return (
              <TouchableOpacity
                touchRetentionOffset={ExNavigator.Styles.barButtonTouchRetentionOffset}
                onPress={() => {that.goToAddDevice();}}
                style={ExNavigator.Styles.barRightButton}>
                <Text style={ExNavigator.Styles.barRightButtonText}>+</Text>
              </TouchableOpacity>
            );
        }
    }}
/>
```

NavigatorIOS:
![image](https://cloud.githubusercontent.com/assets/51059/11158963/cee6e362-8a29-11e5-94eb-6ee83bffdd3d.png)
ExNavigator:
![image](https://cloud.githubusercontent.com/assets/51059/11158951/b1faf0ae-8a29-11e5-90dc-482506e61011.png)

**Comment by ide** [comment]
Add right padding/margin to the TouchableOpacity component in this case. There's not much we can do aside from computing the size of the button and then trying to position it. ExNavigator prioritizes letting you write code and customize things within some relatively wide guidelines rather than targeting a highly specific look (ex: following Apple to the pixel).

**Comment by cancan101** [comment]
@ide that is what I assumed these props would do:

``` jsx
touchRetentionOffset={ExNavigator.Styles.barButtonTouchRetentionOffset}
style={ExNavigator.Styles.barRightButton}
```

**Comment by ide** [comment]
barRightButton's right spacing is for icons that are about 40-50px wide. You could either override the right spacing to your desired look or make your Text component wider.

**Comment by cancan101** [comment]
Is there no way to do the styling to be more robust to changes in text size?

**Comment by ide** [comment]
You could write that code yourself. It probably ends up being asynchronous since you need to listen to layout changes.
