### ISSUE TITLE
touchRetentionOffset

### ISSUE THREAD

**Issue by cancan101** [exponentjs/ex-navigator#34]
What is the `touchRetentionOffset` property being set on `TouchableOpacity` ? I don't see that property in the React Native docs.

**Comment by cancan101** [comment]
Perhaps it is `EdgeInsetsPropType` : https://github.com/facebook/react-native/commit/f331d2a8441fa024a43401953d8eae07f52c4919

**Comment by ide** [comment]
It's a new prop -- code/documentation here https://github.com/facebook/react-native/commit/f331d2a8441fa024a43401953d8eae07f52c4919

**Comment by cancan101** [comment]
I linked to that commit already. This issue should stay open as there are places that should be changed in ExNavigator: https://github.com/exponentjs/ex-navigator/blob/bf76fe8dd10ad5e0ca0ac1357f7016926ee77cb7/ExRouteRenderer.js#L109

**Comment by ide** [comment]
Yeah. I'll update it when the next RN RC goes out.
