### ISSUE TITLE
Error when trying to use replace on the initalRoute

### ISSUE THREAD

**Issue by sercanov** [exponentjs/ex-navigator#35]
I tried navigator.replace on the initialRoute got the error below,
![ekran resmi 2015-11-18 23 58 24](https://cloud.githubusercontent.com/assets/10291644/11255701/519b1f6a-8e50-11e5-8e5e-5c8bb5af5416.png)

I managed to go to line 220 on ExRouteRenderer and changed `this._previousRoute.scene.componentDidBlur` to `this._previousRoute.componentDidBlur` seems it fixed but it may broke somewhere else. 

Here is my ExNavigator component ;
      `<ExNavigator
          initialRoute={DaRouter.getHomeRoute()}
          style={{ flex: 1 }}
          showNavigationBar={false}
      />`

and navigating block ;
`this.props.navigator.replace(DaRouter.getLogin());`

Am I missing something here or is it just a bug?

**Comment by ide** [comment]
Could you try upgrading to 0.3.0?

**Comment by sercanov** [comment]
Committed in five minutes and It worked flawlessly!

I don't know how do you dealing with all this subjects on react-native, exponent, facebook and many others that I don't know but you're doing great work.

Appreciated :)
