### ISSUE TITLE
npm install @exponent/react-native-navigator --save failed

### ISSUE THREAD

**Issue by sparkdreamstudio** [exponentjs/ex-navigator#37]
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@exponent/react-native-navigator" "--save"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code E404

npm ERR! 404 Not Found: @exponent/react-native-navigator
npm ERR! 404 
npm ERR! 404 '@exponent/react-native-navigator' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'MyProject'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sungongren/Desktop/Henry/study/React-Native/MyProject_0.14.0_mac_react-native.cn/npm-debug.log

**Comment by ccheever** [comment]
Hi-

You're using too old of a version of node/npm, and so the `@username/module` syntax isn't supported.
Upgrade to something like node v4.2.2 (I recommend using https://github.com/creationix/nvm ) and this should be fixed.

C

**Comment by sparkdreamstudio** [comment]
thx

**Comment by ccheever** [comment]
Actually, I see you're using a recent version of node, I'm not sure why this is happening.

**Comment by ide** [comment]
@sparkdreamstudio are you connecting to the main npm server and not a mirror? For the record the package is here: https://www.npmjs.com/package/@exponent/react-native-navigator.

**Comment by sparkdreamstudio** [comment]
i connect to a mirror

**Comment by ide** [comment]
I'm not sure there's much we can do to help you. I recommend asking the maintainers of the mirror to make sure they are mirroring all of the modules in the main npm server.

**Comment by sparkdreamstudio** [comment]
OK,thx
