### ISSUE TITLE
 Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `NavigatorNavigationBar`.'

### ISSUE THREAD

**Issue by sparkdreamstudio** [exponentjs/ex-navigator#38]

**Comment by ide** [comment]
Please provide a stack trace and more debugging information.

**Comment by sparkdreamstudio** [comment]
![93263a54-ec43-4569-8973-addf97c76c2d](https://cloud.githubusercontent.com/assets/1477665/11265579/51c31c62-8ed8-11e5-809e-cf516ddfb87a.png)

**Comment by ide** [comment]
I think you have a bug in your code. If you find a bug in ExNavigator please open a new issue.

**Comment by shohey1226** [comment]
I do see similar one due to babel6 on RN0.18. Fixed with `require().default` like below. 

```
  let EditBlockerButton = require('./containers/EditBlockerButton').default;
```
