### ISSUE TITLE
Sample for navigation bar styling ?

### ISSUE THREAD

**Issue by melihmucuk** [exponentjs/ex-navigator#4]
I need sample for navigation bar styling. For example how can I change navigation bar background color and title color ?

**Comment by jadsonlourenco** [comment]
Is good have this example, for me using the **style** prop on `<ExNavigator>` don't do the job, but the **sceneStyle** works well to scene styles.

Also an example showing how to use the new props of the last version 0.2.2: **augmentScene** and **renderNavigationBar**, will be great. I try the _renderNavigationBar_ but don't do anything...

**Comment by ide** [comment]
ExNavigator takes a prop called `navigationBarStyle`. Could you try that and see if it works for you?

**Comment by melihmucuk** [comment]
Ohh sorry, I didn't see navigationBarStyle props! It works. @ide

**Comment by ide** [comment]
Great! Thanks for confirming.
