### ISSUE TITLE
FloatFromBottom with a new Navigation Bar

### ISSUE THREAD

**Issue by rmdort** [exponentjs/ex-navigator#42]
I am using ExNavigator in my RN app and i want to push a new route with floatFromBottom, but the Navigation Bar is on top of my View and the left button,right button and title cross-fades.

Is there a way to push a new route with floatFromBottom with a new navigation bar that overlays the previous scene?

**Comment by ide** [comment]
Yes, use a second Navigator.

**Comment by rmdort** [comment]
I have tried using ExNavigator in the new route, but the previous Navigation Bar is still on top. Any ideas why?

**Comment by ide** [comment]
Are you nesting them correctly? Make sure the modal is displayed via the outer navigator.

**Comment by rmdort** [comment]
I am actually using ExNavigator to render the modal

```

var routes = {
    getNewRoute() {

        return {
            getSceneClass(){

                return require('./containers/main');
            },
            getTitle(){

                return 'Search'
            },
            configureScene(){

                return ExNavigator.SceneConfigs.FloatFromBottom
            },

        }
    }
}


this.props.navigator.push(routes.getNewRoute())
```

The scene floats from bottom but the Navigation Bar cross fades. Is there anyway to get the Navigation bar to float from bottom as well for the new route

**Comment by thorbenandresen** [comment]
@rmdort My example might help you. I have a modal on top of a ExNavigator which covers the entire screen. You can then place another ExNavigator in the modal. https://github.com/Thorbenandresen/ExNavigatorExampleModal

btw. the modal comes from the top, but you can easily switch that to bottom - see the Jason Brown's link provided in the repo
