### ISSUE TITLE
Imperatively Change Route Title

### ISSUE THREAD

**Issue by cancan101** [exponentjs/ex-navigator#44]
Provide a way to imperatively change the title shown in the ExNavigator for the current route.

**Comment by ide** [comment]
The way to do this is to implement renderTitle with a custom view that has an imperative method. There are several possible transitions for setting a title (e.g. cross-fading, sliding in, fading out then fading in) so ExNavigator lets you implement whatever behavior is right for your app.

**Comment by cancan101** [comment]
@ide how do I get a reference to the view returned by `renderTitle`?

**Comment by ide** [comment]
``` js
renderTitle={() => <View ref={c = { this._title = c; } />}
```

It's all standard React and JS all the way down.
