### ISSUE TITLE
cannot read 'NODE_ENV'

### ISSUE THREAD

**Issue by mimamuh** [exponentjs/ex-navigator#50]
Tried to use ExNavigator like described on the readme and got the exeption in the invaraint-function of browser.js file in line @ 25:0. 
It tries to get the environment variable (if (process.env.NODE_ENV !== 'production')) but they are undefined?
I use it with react-native 0.15. Any idea?

**Comment by ide** [comment]
You need to require react-native in your code before anything else. It will set up process.env for you.

**Comment by mimamuh** [comment]
Got it - it was a bad written polyfill of mine .. but your answer helped me to recognise it after long search, thx! :)
