### ISSUE TITLE
The way to propagate changes in props with navigator

### ISSUE THREAD

**Issue by shohey1226** [exponentjs/ex-navigator#52]
This might be off the topic but I think many people would consider how to deal with the idea of [smart/dumb compoent](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.sbmcq06wp) on react-native, because there are a lot of use cases that the first/initial route, route[0], has information and the rest routes are dumb component. For example, the component of ListView(parent) has the data and the each list item(child component) is just using the part of the parent's data. With React, when there is a change on parent's data, the particular change related to the child component is propagated by using the props. 

I'm using "replace" to realize this without propagating props, like below.  I would like to know what is the best way to handle this. And is it possible to have the API to deal with this in the future? 

```
  # this is on parent component and the change is pushed to props(I'm using Redux)
  componentWillReceiveProps(nextProps){
    this.props.hubs.map((currentHub) => {
      nextProps.hubs.map((hub) => {
        if(currentHub.updatedAt !== hub.updatedAt){
          this.props.navigator.getCurrentRoutes().map((r, index) => {
            if(r.getHubId && ( r.getHubId() === hub.objectId ) ){
              let route = Router.getHubRoute(hub);
              this.props.navigator.replaceAtIndex(route, index);
            }
          });
        }
      })
    })
```

**Comment by ide** [comment]
You probably want to write this code in the owner of the Navigator component, not in the first screen component. Also, each screen should be a smart component.

``` js
class App extends Component {
  constructor(props, context) {
    super(props, context);
    this.state = { routes: [Router.getInitialRoute()] };
  }

  render() {
    return (
      <ExNavigator
        initialRouteStack={this.state.routes}
        ref={c => { this._navigator = c; }}
      />
    );
  }

  componentDidUpdate(prevProps, prevState) {
    // compare this.state.routes to prevState and call this._navigator.push/pop/replace
  }
}
```

But I think this is too complicated. You should just call push/pop when you need to.

**Comment by shohey1226** [comment]
@ide  Thank you for your comment.  Agreed. It's a way complicated..  just regarding each scene as smart component and updating with the change is simple way to handle this.  Thanks again.
