### ISSUE TITLE
paddingRight on barBackButton pushes off screen

### ISSUE THREAD

**Issue by zebulgar** [exponentjs/ex-navigator#55]
Was playing around with this and was facing an issue where my back button was getting pushed off screen. I fixed this by changing the barBackButton style to only be 5px of paddingRight:

Before:
![screenshot 2015-12-04 17 35 54](https://cloud.githubusercontent.com/assets/1158032/11605184/ab230642-9aad-11e5-88fe-4287d66dc3bd.png)

After:
![screenshot 2015-12-04 17 36 10](https://cloud.githubusercontent.com/assets/1158032/11605185/b11ac4a4-9aad-11e5-8119-f4c764b993b3.png)

Not really sure what the expected behavior should be. Maybe that it changes from "Clipboard" to "Back" when the title of the current screen gets too long. Or gets rid of the text alltogether? Note this is on an iPhone 5 simulator.

**Comment by zebulgar** [comment]
This was due to using an older version of RN if anyone stumbles across this

**Comment by ide** [comment]
Thanks for the update =)
