### ISSUE TITLE
Accessing this.props.navigator.push from views that are not part of either initialRoute or renderScene.

### ISSUE THREAD

**Issue by rnagella** [exponentjs/ex-navigator#56]
Hello Exponent Team,

**this.props.navigator.push** method available to Views that are pushed to ExNavigator or to the views that set via initialRoute.

Can we able to access **this.props.navigator.push** property, if the view is not either of the above two options. **for ex**: I have this SideMenu with a Text and onPress of this Text I would like to push the View to ExNavigator. But, **this.props.navigator.push** method is not available in this context because this scene is not rendered using ExNavigator.
https://github.com/rnagella/ExNavigatorWithSideMenu/blob/master/src/Menu.js#L20

Is there a way to access this.props.navigator.push from non ExNavigator Views?
**Thank you for your time.**

Here is the sample app that I created to show case my thoughts. 
https://github.com/rnagella/ExNavigatorWithSideMenu

Note: Please, swipe Home screen to see the side menu.
![home](https://cloud.githubusercontent.com/assets/3255325/11645062/3d96084e-9d1f-11e5-971a-09fbd5a8a432.png)
![aboutus](https://cloud.githubusercontent.com/assets/3255325/11645061/3d95ac5a-9d1f-11e5-9c1d-d2400404c8a6.png)
![menu](https://cloud.githubusercontent.com/assets/3255325/11645063/3da26d8c-9d1f-11e5-9a14-b2fdf1dcb8b8.png)
![menuerror](https://cloud.githubusercontent.com/assets/3255325/11645064/3da85fc6-9d1f-11e5-8aa8-e0e835ad2aad.png)

**Comment by ide** [comment]
You need access to an ExNavigator component instance to call `push` -- there's no way around it. You should make your ExNavigator instance available to your side menu component if you need to push new scenes. How you do this is totally up to you; it's all code.
