### ISSUE TITLE
Handling nested navigator navbars correctly

### ISSUE THREAD

**Issue by aksonov** [exponentjs/ex-navigator#57]
When i push to the screen with own exnavigator, new navbar is fully hidden over old (parent) navbar. When i set sceneStyle.paddingTop, then I will see both navbars correctly, but it is not desired behaviour - i just want to see new navbar, like it is done in iOS Navigator. How to achieve this? Thanks.

**Comment by ide** [comment]
Try using three navigators:
- Root Navigator (without a NavigationBar)
  - Scene 1 with a Navigator
  - Scene 2 with a Navigator

You push Scene 2 using the Root Navigator instead of the Scene 1 Navigator.

**Comment by aksonov** [comment]
So to go from Scene 1 to Scene 2 i should use navigator.parentNavigator.push(..) ?

**Comment by ide** [comment]
Yes, or save a direct reference to the parent navigator. Either works.

**Comment by aksonov** [comment]
Looks a little bit hacky, is there any problem with nested navigators (if i would implement custom nav bar which will be hidden if nested nav bar is shown)?
