### ISSUE TITLE
Issues with ExNavigator Containing ExNavigator

### ISSUE THREAD

**Issue by cancan101** [exponentjs/ex-navigator#61]
I have an ExNavigator and I push a route that renders a scene with another ExNavigator. Both ExNavigators have `showNavigationBar={true}`. This is what I see first.
![image](https://cloud.githubusercontent.com/assets/51059/11827238/b0582e04-a358-11e5-989e-e4fafd1aa5a1.png)

When I push `Next`, I then get the "desired" behavior:
![image](https://cloud.githubusercontent.com/assets/51059/11827274/e69aca76-a358-11e5-8b3e-e695fb9367d9.png)

**Comment by ide** [comment]
So I think what you want to do is introduce a third navigator:
- RootNavigator (no nav bar)
  - Navigator 1
  - Navigator 2

In your example you'd push the second navigator using `rootNavigator.push(routeWithNavigator2)`. Does this make sense?

**Comment by cancan101** [comment]
Yes, that worked. I just need to handle the backbutton / left button to pop the stack (something I would have had to deal with even in my initial approach).
