### ISSUE TITLE
Root navbar buttons tappable when inside another route

### ISSUE THREAD

**Issue by samuelkraft** [exponentjs/ex-navigator#64]
I have a navigator + navbar which displays a button with renderRightButton() (left screen in screenshot). After pushing a new view on the navigator the right button is still tappable (even though it's not visible). When inspecting the navbar I can see the button. It's like the old navbar is positioned beneath the new view and is still tappable. Any idea how to solve this? 
![artboard](https://cloud.githubusercontent.com/assets/2223418/11899490/9990446a-a59f-11e5-9484-ab2d50cd81bd.png)

**Comment by jamieathans** [comment]
The way I solved this issue was was to define a flag in the getXXXRoute method of my router and in the onWillBlur/onDidFocus methods, set this flag false/true.

Check the flag in the button handler and just return if false.

**Comment by ide** [comment]
This is a bug with the upstream Navigator. Probably need to use pointerEvents instead of opacity somewhere in the NavigatorNavigationBar code.

**Comment by samuelkraft** [comment]
Oh ok, thanks. Closing this since it's not specific to ExNavigator.

Related issue: https://github.com/facebook/react-native/issues/4559
