### ISSUE TITLE
Change navigator title dynamically

### ISSUE THREAD

**Issue by JimGeek** [exponentjs/ex-navigator#67]
I have been playing with react native for quite some time. But during one of my application, I have encountered the issue with ex-navigator. I have a web view which open the given URL, now my application requires to update the title of navigator to the title of the webpage loaded when loading finishes. I have searched many places about this but no success. Is it possible to change the navigator title dynamically if yes how should I do that.

**Comment by ide** [comment]
Implement renderTitle with a component that is subscribed to a data store / event emitter / exposes a method that sets the title component's state and causes it to rerender.
