### ISSUE TITLE
Both titles appear on the navigation bar (previous and current) 

### ISSUE THREAD

**Issue by eranbes** [exponentjs/ex-navigator#70]
I was looking for a flag or property to hide the previous one but could not find it. 
I know that I can use render but was looking for something simpler.
Please follow the link to see the issue.

https://www.dropbox.com/s/c8cfimqy35l18w4/Screenshot%202016-01-08%2016.37.57.png

**Comment by ide** [comment]
The previous title appears because ExNavigator tries to helpfully use the previous scene's title in the back button. If you don't want this, specify the `renderBackButton` prop on the ExNavigator component itself.
