### ISSUE TITLE
Is It Possible To Have 'No' Transition?

### ISSUE THREAD

**Issue by bfarrgaynor** [exponentjs/ex-navigator#75]
Being able to use animated transitions is awesome. But I want to be able to flip between routes without animation and just have it quickly pop there like you would with a Tab Bar. Like 1 frame it's route A and in the next frame it's route B. 

Navigator.SceneConfigs.FadeAndroid comes close, but if I just simply accelerate the animation it has this undesirable flicker effect.

Any ideas? Thanks!

**Comment by ide** [comment]
I think it's a matter of writing a SceneConfig that transitions immediately. I'm not sure what it'd look like but that's where I'd look. There's no way to say "don't apply any scene config" -- you always have to provide a SceneConfig. That's more related to Navigator than ExNavigator, so I'd recommend reading the Navigator source.
