### ISSUE TITLE
@exponent/react-native-navigator not found in NPM registry

### ISSUE THREAD

**Issue by jbadeau** [exponentjs/ex-navigator#79]
I am getting not found when i try to get @exponent/react-native-navigator from npm. It's been like this for a few days now? Any ideas?

**Comment by ide** [comment]
Your local npm config might be broken. The package is here: https://www.npmjs.com/package/@exponent/react-native-navigator. Try to connect directly to the official npm registry if you're using a mirror.

**Comment by jbadeau** [comment]
I tried the official links. Seems the global registry was not working. But it is resolved since the last 10 minutes. :)

was not working
http://registry.npmjs.org/@exponent/react-native-navigator/-/react-native-navigator-0.3.7.tgz

mirrors were working
http://registry.npmjs.eu/@exponent/react-native-navigator/-/react-native-navigator-0.3.7.tgz
http://registry.npmjs.org.au/@exponent/react-native-navigator/-/react-native-navigator-0.3.7.tgz
