### ISSUE TITLE
LoadingContainer?

### ISSUE THREAD

**Issue by alinz** [exponentjs/ex-navigator#8]
@ide You mentioned in your [article](https://medium.com/the-exponent-log/routing-and-navigation-in-react-native-6b27bee39603#.d9pvlejru) that you guys have written `LoadingContainer` to defer screen to load. Has that component released as open source? if so would you please provide me the link?

Thanks,

BTW: ExNavigator is amazing. thanks for the code!

**Comment by ide** [comment]
LoadingContainer is currently not open-source because it has some dependencies on our product code (logos and things like that) but we would like to eventually share it. @brentvatne is the guy behind it.

**Comment by alinz** [comment]
thanks for feedback! I think I will start writing my own until you guys make it open source!

**Comment by ide** [comment]
Here's our LoadingContainer for those who are interested: https://github.com/exponentjs/react-native-loading-container.
