### ISSUE TITLE
Navigation buttons can be tapped even when not displayed.

### ISSUE THREAD

**Issue by masom** [exponentjs/ex-navigator#82]
Using the navigator to navigate from a view with a right button to a view without right button will still allow events to be dispatched to the previous route right button.

ex:
![image](https://cloud.githubusercontent.com/assets/438456/12493717/590924fa-c054-11e5-912d-3cd87ef89a15.png)
![iphone 5 - iphone 5 ios 9 2 13c75 2016-01-21 15-34-04](https://cloud.githubusercontent.com/assets/438456/12493745/83e00a04-c054-11e5-822b-81223294b5de.jpg)

**Comment by samuelkraft** [comment]
It's an issue with Navigator: https://github.com/facebook/react-native/issues/4559

**Comment by masom** [comment]
Oh geez, thanks. I was hoping it would be in ex-navigator, faster to get fixes than in RN.
