### ISSUE TITLE
build error in XCode

### ISSUE THREAD

**Issue by bheithaus** [exponentjs/ex-navigator#83]
in this latest update to 0.4.1, I see that you changed to using react-clone-referenced-element, this seems to be related to that

I am getting this build error in XCode, trying to implement ex-navigator in a brand new react-native 0.18.1 app:

uncaught error Error: UnableToResolveError: Unable to resolve module react from /Users/brianheithaus/Code/ReactNativeProjects/IVW/node_modules/@exponent/react-native-navigator/node_modules/react-clone-referenced-element/cloneReferencedElement.js: Invalid directory /Users/node_modules/react

  message: 'Unable to resolve module react from /Users/brianheithaus/Code/ReactNativeProjects/IVW/node_modules/@exponent/react-native-navigator/node_modules/react-clone-referenced-element/cloneReferencedElement.js: Invalid directory /Users/node_modules/react',
  name: 'UnableToResolveError',
  type: 'UnableToResolveError' }

It is definitely true, that is an invalid directory!  

I thought I'll share here, in case I'm not be the only one encountering this issue

Thanks for any suggestions

**Comment by ide** [comment]
Can you try using npm 3 and deleting + reinstalling node_modules?

**Comment by bheithaus** [comment]
Thank you for the help @ide!  It worked perfectly.  npm3 installs all deps in flat directory structure, so, problem solved :+1: 

I ran:
(delete /node_modules)
`npm install -g npm3`
`npm3 install`
