### ISSUE TITLE
Pass Props to the route

### ISSUE THREAD

**Issue by tantou** [exponentjs/ex-navigator#86]
Can `ExNavigator` support pass props to the route?
The `NavigatorIOS` support to pass props to the route

**Comment by ide** [comment]
We aren't trying to copy NavigatorIOS but anyway you could access navigator.props.X.

**Comment by jordangarside** [comment]
If I try to set a variable or callback on navigator.props.X I get the error:
`Attempted to assign to readonly property.`

Is there any other way to do this?

**Comment by jordangarside** [comment]
@tantou
Since you can't change `this.props.navigator.props` because it's readonly,
the easiest way to do something like passProps is this

Add some additional keys to your route

```
this.props.navigator.push(Object.assign({}, waypointSearchRoute, {
    componentType: 'someType',
    componentCallback: () => {
        console.log(' You called me back ');
    },
}));
```

Access the callback in your component

```
let currentRoutes = this.props.navigator.getCurrentRoutes();
let currentRoute  = currentRoutes[ currentRoutes.length - 1 ];
console.log(currentRoute.componentType);
currentRoute.componentCallback();
```

I think this is a somewhat significant use case.
