### ISSUE TITLE
Compatibility with container components?

### ISSUE THREAD

**Issue by mikefowler** [exponentjs/ex-navigator#87]
I'm using Alt.js and making use of the provided [`connectToStores`](https://github.com/altjs/connect-to-stores#how-to-use). When I do so, I get some funny behavior when using these wrapped components as scenes in ExNavigator.

![screen shot 2016-02-01 at 10 39 22 am](https://cloud.githubusercontent.com/assets/744542/12727101/1a8982fe-c8d0-11e5-863a-2f4655828857.png)

Namely, as evidenced in the screenshot, the component is constructed twice, and `componentDidUpdate` is called more than expected (nearly double), and some of those calls are missing all of the expected props except for the `navigator` prop, the instance of `ExNavigator`.

It's worth noting that these same scene components have been working great with React Native's `Navigator`, so this is a bit mystifying. In the screenshot, the component being rendered looks like this:

``` js
class LoginViaFacebook extends Component {
  static getStores() {
    return [AuthStore];
  }

  static getPropsFromStores() {
    return {
      auth: AuthStore.getState(),
    };
  }

  constructor(props: Object) {
    super(props);
    // Why is this called twice?
    console.log('LoginViaFacebook#constructor');
  }

  componentDidMount() {
    console.log('LoginViaFacebook#componentDidMount');
  }

  componentDidUpdate(): void {
    // this.props.auth should *always* exist, even if it's just an empty object
    console.log(this.props);
  }
}

module.exports = connectToStores(LoginViaFacebook);
```

Any insight or followup questions welcome.

**Comment by ide** [comment]
I'm not sure what's going on but I would use the debugger and look at the call stacks at various points to see if that provides any clues.

**Comment by mikefowler** [comment]
I've been doing so and haven't run across anything that stands out so far. Was just curious if you or any of the Exponent team have experienced anything like this, as container components are becoming fairly common in many of the Flux implementations.

**Comment by ide** [comment]
We use react-redux and it's working fine. I think it uses a container approach (though unrelatedly, containers usually end up being a pain...)

**Comment by mikefowler** [comment]
Alright. Thanks for the followup, @ide.
