### ISSUE TITLE
@exponent/react-native-navigator is not on npm

### ISSUE THREAD

**Issue by pietropizzi** [exponentjs/ex-navigator#9]
When running `npm install @exponent/react-native-navigator --save` you get `'@exponent/react-native-navigator' is not in the npm registry.`

Are you maybe using a private registry where this is available? Would be great to have it as an npm package

**Comment by ide** [comment]
It's publicly available here: https://www.npmjs.com/package/@exponent/react-native-navigator and we use in in our package.json like 

``` json
  "dependencies": {
    "@exponent/react-native-navigator": "^0.2.4",
```

**Comment by pietropizzi** [comment]
Thanks for the quick response. It's interesting that it doesn't work for me. Which version of npm are you using? I am trying it on `v2.14.2`.

Also when you use the search on npm like so: https://www.npmjs.com/search?q=react-native-navigator your package does not come up.

**Comment by ide** [comment]
I'm on npm 2.14.8 though it has been working for awhile.

**Comment by pietropizzi** [comment]
Ok so I have found the issue. We are using our own private registry build with [Sinopia](https://www.npmjs.com/package/sinopia). When running `npm install` it first goes to our server and if it can't find it there it goes to the public one. Apparently there is some bug in that pipeline when the package is scoped.

Also for the fact that you can not find scoped packages on npm, here is the issue: https://github.com/npm/npm/issues/8453

**Comment by ide** [comment]
@pietropizzi Thanks for the follow-up. To workaround the issue you could try installing the module directly from GitHub with `npm i exponentjs/ex-navigator#5a4191e9b`, for example. We do a lot of updates and tend not to use Git tags / GH releases, but do try to mention in the commit titles when there is a new npm version, so you could adjust the Git commit hash in the package.json entry accordingly.

**Comment by pietropizzi** [comment]
@ide thanks. I was able to install it with `npm install --registry=https://registry.npmjs.org` so going straight to the public registry.

**Comment by ide** [comment]
Great, that's even better!
