### ISSUE TITLE
unable to resolve module .../@exponent/react-native-navigator/node_modules/react-clone-referenced-element/cloneReferencedElement.js

### ISSUE THREAD

**Issue by rnagella** [exponentjs/ex-navigator#90]
When importing ExNavigator with in app fails with below error message 
This apps is built with React Native dependencies 0.19.0
This can be resolved by importing the React Native module using import instead require.  
`SOLUTION`
i.e., `import React from 'react-native'` instead  `let React = require('react');` with in **@exponent/react-native-navigator/node_modules/react-clone-referenced-element/cloneReferencedElement.js**

![simulator screen shot feb 3 2016 12 01 01 pm](https://cloud.githubusercontent.com/assets/3255325/12790283/967e0fe2-ca6f-11e5-9bb7-1463dba10192.png)

**Comment by aawaheed** [comment]
same issue while trying out https://github.com/Thorbenandresen/ExNavigatorExample with react-native:0.19.0

**Comment by oney** [comment]
Replace `node_modules/@exponent/react-native-navigator/node_modules/react-clone-referenced-element/cloneReferencedElement.js` `line 3` to
```javascript
let React = require('react-native/node_modules/react');
```

**Comment by jayesbe** [comment]
Also having this issue

**Comment by SpaceK33z** [comment]
Also had this issue. It's related to https://github.com/ide/react-clone-referenced-element/issues/3.
