### ISSUE TITLE
How to change RightButton after pushing route?

### ISSUE THREAD

**Issue by oney** [exponentjs/ex-navigator#92]
After pushing route, how to change RightButton?

``` javascript
this.props.navigator.push({
  renderScene() {
    return (<Setting navigator={navigator} />);
  },
  renderRightButton() {
    return (
      <TouchableHighlight>
        <Text>Save</Text>
      </TouchableHighlight>
    );
  },
});
```

I want to change RightButton "Save"(e.g color, disable) in `Setting` component.
In iOS, we can easily `self.navigationItem.rightBarButtonItem = anotherButton;` to set it.

**Comment by ghost** [comment]
Might be late but here is how i did it.
Create a RightButton class that has state variables for your states e.g disable, enabled.
Create an eventEmitter in router and pass this to your Scene class in renderScene and RightButton class in renderRightButton.
You can use this emitter to emit event from your scene class. Catch the event in RightButton class and change the state variable of your RightButton class. Have the render method of the RightButton class render different states (disabled, color) based on the state variable.

**Comment by Andreyco** [comment]
@erfanayaz This is what I do as well. Found no better way to do so...

**Comment by ide** [comment]
Yep, use an EventEmitter.
