### ISSUE TITLE
Shared Background

### ISSUE THREAD

**Issue by graywolf336** [exponentjs/ex-navigator#94]
This is a result of https://github.com/aksonov/react-native-router-flux/issues/205. But what I'm trying to accomplish is to have a parent view have a background image and then any of the child elements share their parent's background image. I tried it with `react-native-router-flux` and they pointed me here, so then I tried it with the modal example project but it didn't work there either.

Any pointers on how this can be accomplished? Thanks.

**Comment by ClaytonAnderson** [comment]
You can use the sceneStyle prop on ExNavigator to set a transparent background. Something like this should work:

```
render() {
    return (
        <View style={{ flex: 1 }}>
            <AppBackground />
            <ExNavigator
                initialRoute={router.getHomeRoute()}
                sceneStyle={{ backgroundColor: 'transparent' }} />
        </View>
    );
}
```

**Comment by graywolf336** [comment]
@ClaytonAnderson Awesome! That indeed did work. :+1:

**Comment by joshuapinter** [comment]
I'm trying to set the background color of ExNavigator's initial scene/route and it doesn't seem to be working. 

``` javascript
<ExNavigator
        initialRoute={Router.getHomeRoute()}
        styles={{ flex: 1 }}
        sceneStyle={{ paddingTop: 64, backgroundColor: '#000000' }} />
```
