### ISSUE TITLE
renderRightButton README example doesn't work.

### ISSUE THREAD

**Issue by joshuapinter** [exponentjs/ex-navigator#99]
``` javascript
renderRightButton() {
        return (
          <Button onPress={() => { console.log('Tapped right button'); }}>
            Log
          </Button>
        );
      },
```

This generates an error: 

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `NavigatorNavigationBar`.

**Comment by ide** [comment]
I think this is because you need to define the Button component. You can render whatever view you want.

**Comment by joshuapinter** [comment]
I double checked and it's being imported properly from `react-native`.

![screenshot 2016-02-24 14 21 54](https://cloud.githubusercontent.com/assets/180819/13301413/fcaa65a2-db01-11e5-9389-b4eabb1afd33.png)

**Comment by ide** [comment]
React Native doesn't ship with Button --- try console.logging it.

**Comment by joshuapinter** [comment]
Of course! Sorry, still getting used to RN. Thanks for your help.
